// <auto-generated />
using System;
using FlightTour_Service.DataAccess.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightTour_Service.Migrations
{
    [DbContext(typeof(SqliteFlightDbContext))]
    partial class SqliteFlightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("FlightTour_Service.DataDomain.FlightData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("aircraft")
                        .HasColumnType("TEXT");

                    b.Property<string>("airlineCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("airlineName")
                        .HasColumnType("TEXT");

                    b.Property<string>("arrivalDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("classType")
                        .HasColumnType("TEXT");

                    b.Property<string>("classTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("destination")
                        .HasColumnType("TEXT");

                    b.Property<string>("destinationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("flightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("flightNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("leaveDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("origin")
                        .HasColumnType("TEXT");

                    b.Property<string>("originName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("priceAdult")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("priceChild")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("priceInfant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("proposalId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("seat")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("stars")
                        .HasColumnType("INTEGER");

                    b.Property<string>("statusName")
                        .HasColumnType("TEXT");

                    b.Property<string>("terminal")
                        .HasColumnType("TEXT");

                    b.Property<string>("ticketType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ticketTypeLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("uniqueKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FlightData");
                });
#pragma warning restore 612, 618
        }
    }
}
